---
- name: Récupérer et modifier le fichier kubeconfig
  hosts: k3s  # ou le groupe spécifique dans ton inventaire
  tasks:
    - name: Copier le fichier kubeconfig localement
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig-k3s.yaml
        flat: yes

    - name: Modifier l'adresse du serveur dans kubeconfig
      local_action:
        module: lineinfile
        path: ./kubeconfig-k3s.yaml
        regexp: '^    server: https://127.0.0.1:6443'
        line: '    server: https://{{ ansible_host }}:6443'
      delegate_to: localhost

    - name: Afficher le contenu du fichier kubeconfig modifié
      local_action:
        module: command
        args:
          cmd: cat ./kubeconfig-k3s.yaml
      delegate_to: localhost
